#环境配置
spring:
  application:
    name: like-admin-server
  profiles:
    active: @profileActive@
  #    active: develop
  ## ==========================jsckson配置=====================================
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-ignored-properties: true
      fail_on_unknown_properties: false
    parser:
      allow-unquoted-control-chars: true
      allow-single-quotes: true
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  ## ==========================jsckson配置=====================================

  ## ==========================sessionc存储=====================================


## =====================switch必须为true=============================
## jdbc开关key---sika.code.jdbc.switch

sika:
  code:
    jdbc:
      fire: true
    redis:
      fire: true
    log:
      controller:
        fire: true
      sql:
        fire: true
## =====================switch必须为true=============================
## ==========================开关配置=====================================

## =========================mybatis配置===============================
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  banner: false