server:
  port: 8101
  tomcat:
    accept-count: 1024
    max-threads: 1024
debug: false
headImagePath: /usr/share/nginx/html/dist-quasar-admin/imgs/head/
sika:
  code:
    workspace:
      worker-id: 2
      data-center-id: 1
    rabbit:
      sender:
        log-fire: true
        ack: true
    ## ==========================restTemplate配置begin=====================================
    rest:
      template:
        maxTotal: 1500
        defaultMaxPerRoute: 1500
        connectTimeout: 12000
        readTimeout: 90000
        connectionRequestTimeout: 200
        bufferRequestBody: false
    ## ==========================restTemplate配置end=====================================
    auth:
      # jwt秘钥
      jwt-secret: ETZZN3KX194HXI82
      server-name: risk-system-server
    thirdparty:
      url:
        erpRequestDomain: http://erp-service
        erpRequestDomainHttps: https://api-gateway.52rental.com/oauth-server
        sjmhRequestDomainHttps: https://api.shujumohe.com/octopus
      erp:
        appId: 201801010001
        appSecret: cDieLmT10edZYU9diLmFMpMkZLLb1WaSk58wCuK7Nmwnmzz3wDwdYkmzzJNLgiCU
      sjmh:
        partnerCode: lxzp_mohe
        partnerKey: 18063e6db59948ce8ce301062e351fb3
    ################### 异常通知 begin ############################
    exception:
      inform:
        defaultWebHookForDingding:
      ################### 异常通知 end ############################
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
    template:
      mandatory: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enable: true
    hikari:
      # JDBC 配置(驱动类自动从url的mysql识别,数据源类型自动识别)
      core:
        minimum-idle: 10
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 600000
        pool-name: DatebookHikariCP
        max-lifetime: 30000
        connection-timeout: 30000
        connection-test-query: SELECT 1
        jdbc-url: jdbc:mysql://121.89.202.68:3306/sika-design-admin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: SikaDesignAdmin20201225
        driver-class-name:  com.mysql.cj.jdbc.Driver


    ################### mysq end ##########################
    ################### redis 单机版 start ##########################
  redis:
    host: 121.89.202.68
    port: 6379
    timeout: 3000
    password: SikaDesignAdmin20201225
    ################### redis 单机版 end ##########################
    #    cluster:
    #      nodes: localhost:6379
    #    nodes: 134.224.249.36:7000,134.224.249.37:7000,134.224.249.38:7000,134.224.249.36:7001,134.224.249.37:7001,134.224.249.38:7001
    ###        #130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
    ##        #192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001


  #    timeout: 1000 # 连接超时时间（毫秒）
#    pool:
#      max-active: 2000  # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 500     # 连接池中的最大空闲连接
#      min-idle: 50     # 连接池中的最小空闲连接
#      max-wait: 1000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
  redisson:
    mode: single
    single:
      address: 121.89.202.68:6379
    password: SikaDesignAdmin20201225


#设置最大超时时间
ribbon:
  ServerListRefreshInterval: 10  #刷新服务列表源的间隔时间
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  ReadTimeout: 90000
  ConnectTimeout: 90000
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: false
# 服务ribbon的负载配置
erp-service: # ERP服务
  ribbon:
    listOfServers: advance-new-api-gateway.52rental.com/oauth-server


##feign参数优化
feign:
  compression:
    request:
      enabled: true
      mine-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
logging:
  level:
    root: INFO
    com.netflix: OFF
    com.central: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

me:
  zhyd:
    oauth:
      timeout: 15000
      oauthConfig:
        gitee:
          requestClassName: me.zhyd.oauth.request.AuthGiteeRequest
          clientId: e2dc551133ef22c69b988c944f0e35f8e83a8776f6ce883d0bd124b558d359db
          clientSecret: 79c5c3855d748a40b37dc86991ba170f1ff89d27b1bdfe36c6a7b46204eea142
          redirectUri: http://quasar.admin.sikacode.com/api/auth/callback/gitee/anon
        github:
          requestClassName: me.zhyd.oauth.request.AuthGithubRequest
          clientId: eb1a1a1521f1583dca82
          clientSecret: 7c3c1b41ec67280053f1b7767ec5e7123bd10a46
          redirectUri: http://quasar.admin.sikacode.com/api/auth/callback/github/anon
        baidu:
          requestClassName: me.zhyd.oauth.request.AuthBaiduRequest
          clientId: I4Ua5P1v39TlOmHQN02e8rtU
          clientSecret: BD9hqSz3kfk2eAI2a58saHEM2d7IrQFA
          redirectUri: http://quasar.admin.sikacode.com/api/auth/callback/baidu/anon
        weibo:
          requestClassName: me.zhyd.oauth.request.AuthWeiboRequest
          clientId: 3627966137
          clientSecret: f105f965b7f944847204ace0c0a2f3a2
          redirectUri: http://quasar.admin.sikacode.com/api/auth/callback/weibo/anon
        qq:
          requestClassName: me.zhyd.oauth.request.AuthQqRequest
          clientId: 101931120
          clientSecret: d73650b6f64203a45bd3c503a4afa644
          redirectUri: http://quasar.admin.sikacode.com/api/auth/callback/qq/anon
        dingtalk:
          requestClassName:
          clientId:
          clientSecret:
          redirectUri:
        coding:
          clientId:
          clientSecret:
          redirectUri:
        tencentCloud:
          clientId:
          clientSecret:
          redirectUri:
        oschina:
          clientId:
          clientSecret:
          redirectUri:
        alipay:
          clientId:
          clientSecret:
          redirectUri:
          alipayPublicKey:
        wechat:
          clientId:
          clientSecret:
          redirectUri:
        taobao:
          clientId:
          clientSecret:
          redirectUri:
        google:
          clientId:
          clientSecret:
          redirectUri:
        facebook:
          clientId:
          clientSecret:
          redirectUri:
        douyin:
          clientId:
          clientSecret:
          redirectUri:
        linkedin:
          clientId:
          clientSecret:
          redirectUri:
        microsoft:
          clientId:
          clientSecret:
          redirectUri:
        mi:
          clientId:
          clientSecret:
          redirectUri:
        toutiao:
          clientId:
          clientSecret:
          redirectUri:
        teambition:
          clientId:
          clientSecret:
          redirectUri:
        renren:
          clientId:
          clientSecret:
          redirectUri:
        pinterest:
          clientId:
          clientSecret:
          redirectUri:
        stackoverflow:
          clientId:
          clientSecret:
          redirectUri:
          stackOverflowKey:
        huawei:
          clientId:
          clientSecret:
          redirectUri:
        wechatEnterprise:
          clientId:
          clientSecret:
          redirectUri:
          agentId: